# Generated by Django 3.2 on 2021-04-08 13:49

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name='Название')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Название (лат)')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', image_cropping.fields.ImageCropField(upload_to='files')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('git', models.CharField(max_length=250, unique=True, verbose_name='git репозиторий')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('command', models.CharField(max_length=250, verbose_name='Команда')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
