# Generated by Django 3.2 on 2021-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocess',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Каталог'),
        ),
    ]
