# Generated by Django 3.2 on 2021-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprocess',
            name='media_path',
        ),
        migrations.AddField(
            model_name='project',
            name='media_path',
            field=models.CharField(default='', max_length=250, verbose_name='Путь к медиа'),
        ),
    ]
