# Generated by Django 3.2 on 2021-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectprocess_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.CharField(default='', max_length=250, verbose_name='url git репозитория'),
        ),
    ]
