# Generated by Django 3.2 on 2021-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210412_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='', max_length=250, verbose_name='Имя каталога'),
        ),
    ]
