# Generated by Django 3.2 on 2021-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='path',
        ),
        migrations.AlterField(
            model_name='project',
            name='venv_path',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Путь к ВО'),
        ),
    ]
