# Generated by Django 3.2 on 2021-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210413_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release_url',
            field=models.CharField(default='', max_length=250, verbose_name='url релизной версии'),
        ),
    ]
