# Generated by Django 3.2 on 2021-04-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_release_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocess',
            name='port',
            field=models.IntegerField(default=9080),
        ),
    ]
