# Generated by Django 3.2 on 2021-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectprocess_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=160, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=160, null=True, unique=True, verbose_name='Название'),
        ),
    ]
