# Generated by Django 3.2 on 2021-04-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('status', models.CharField(default='создается', max_length=50, verbose_name='Статус')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.env')),
            ],
        ),
    ]
