# Generated by Django 3.2 on 2021-04-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hard',
            field=models.CharField(choices=[('бекенд', 'бекенд'), ('фронтенд', 'фронтенд')], default='простая', max_length=50),
        ),
    ]
