# Generated by Django 3.2 on 2021-04-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_git_url'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maket',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
