# Generated by Django 3.2 on 2021-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_envprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='status',
            field=models.CharField(default='создается', max_length=60, verbose_name='Статус'),
        ),
    ]
