# Generated by Django 3.2 on 2021-04-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Задача'),
        ),
    ]
