# Generated by Django 3.2 on 2021-04-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectprocess_port'),
        ('main', '0003_alter_commit_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Задача'),
        ),
    ]
