# Generated by Django 3.2 on 2021-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_env_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='status',
        ),
    ]
