# Generated by Django 3.2 on 2021-04-15 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
