# Generated by Django 3.2 on 2021-04-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
