# Generated by Django 3.2 on 2021-04-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210420_0814'),
        ('project', '0007_projectprocess_port'),
        ('main', '0010_auto_20210420_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Tsk'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='file',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=250, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='maket',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hard',
            field=models.CharField(choices=[('simple', 'simple'), ('middle', 'middle'), ('hard', 'hard')], default='простая', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], default='фронтенд', max_length=50),
        ),
        migrations.AlterField(
            model_name='task2user',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='User'),
        ),
    ]
