# Generated by Django 3.2 on 2021-04-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environprocess',
            name='command',
            field=models.CharField(default='', max_length=250, verbose_name='Каталог'),
        ),
    ]
