# Generated by Django 3.2 on 2021-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0002_environprocess_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='environ',
            name='status',
            field=models.CharField(default='создается', max_length=60, verbose_name='Статус'),
        ),
    ]
