# Generated by Django 3.2 on 2021-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0002_auto_20210412_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='environ',
            name='state',
            field=models.CharField(default='clean', max_length=60, verbose_name='Состояние'),
        ),
    ]
