# Generated by Django 3.2 on 2021-04-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0003_auto_20210413_0947'),
        ('env', '0004_environ_state'),
    ]

    operations = [
    ]
