# Generated by Django 3.2 on 2021-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0007_alter_environ_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environ',
            name='name',
            field=models.CharField(help_text='must be unique', max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='environ',
            name='state',
            field=models.CharField(choices=[('clean', 'without changes'), ('edited', 'with changes')], default='clean', max_length=60, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='environ',
            name='status',
            field=models.CharField(default='creating', max_length=60, verbose_name='Status'),
        ),
    ]
