# Generated by Django 3.2 on 2021-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0007_alter_environprocess_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environprocess',
            name='path',
        ),
    ]
